# Generated by Django 4.1.2 on 2022-11-20 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_alter_new_options_new_owner_new_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentnew',
            old_name='owner_new',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='new',
            old_name='owner_new',
            new_name='owner',
        ),
    ]
