# Generated by Django 4.1.2 on 2022-11-20 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('new', '0004_rename_owner_new_commentnew_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
