# Generated by Django 4.1.2 on 2022-11-20 21:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('new', '0005_alter_new_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='comments_new',
        ),
        migrations.AddField(
            model_name='new',
            name='commentsnew',
            field=models.ManyToManyField(related_name='commentsnew_owned', through='new.CommentNew', to=settings.AUTH_USER_MODEL),
        ),
    ]
