# Generated by Django 4.1.2 on 2022-11-17 20:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top10', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top10',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='top10',
            name='header',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='top10',
            name='title',
            field=models.CharField(max_length=70),
        ),
    ]
