# Generated by Django 4.1.2 on 2022-11-18 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top10', '0002_alter_top10_content_alter_top10_header_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='top10',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='top10',
            unique_together={('title', 'header')},
        ),
    ]
